### ISSUE TITLE
Latest version randomly stopps working after getting a 504/404

### ISSUE THREAD

**Issue by mickem** [athombv/com.neatorobotics#4]
Not sure if this is a change in the API (from neato) or a change in the error handler of the application.
But with the latest version I keep getting errors which leads the robot to become unavailable in homey.
And it worked perfectly until last week.

What happens is randomly (after 3-4 minutes or so) I get a 504 (Gateway timeout) in response to the getRobotState command.
After this all consecutive requests will generate a 404.
At the same time the robot becomes unavailable in the UI.

So a possible "fix" would be to not throw the error which I think 

```
Request:  { reqId: 3, cmd: 'getRobotState' }
Request:  { reqId: 4, cmd: 'getRobotState' }
Request:  { reqId: 5, cmd: 'getRobotState' }
Request:  { reqId: 6, cmd: 'getRobotState' }
Request:  { reqId: 7, cmd: 'getRobotState' }
==================
==  ERROR INFO  ==
==================
==    REQUEST   ==
==================
Robot request ID: 7
Robot request command: getRobotState
==================
==    RESULT    ==
==================
Robot response status: 504
Robot response text: Gateway Timeout
2018-07-21 11:45:25 [err] [ManagerDrivers] [botvac] [0] Error: Error in robot request
    at NeatoRobot._doRequest (/lib/NeatoRobot.js:122:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Request:  { reqId: 8, cmd: 'getRobotState' }
==================
==  ERROR INFO  ==
==================
==    REQUEST   ==
==================
Robot request ID: 8
Robot request command: getRobotState
==================
==    RESULT    ==
==================
Robot response status: 404
Robot response text: Not Found
2018-07-21 11:45:29 [err] [ManagerDrivers] [botvac] [0] Error: Error in robot request
    at NeatoRobot._doRequest (/lib/NeatoRobot.js:122:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Request:  { reqId: 9, cmd: 'getRobotState' }
==================
==  ERROR INFO  ==
==================
==    REQUEST   ==
==================
Robot request ID: 9
Robot request command: getRobotState
==================
==    RESULT    ==
==================
Robot response status: 404
...
```

**Comment by MatthewWaanders** [comment]
Hi there!

This is intended behaviour since the Neato API is still in beta and not entirely stable.

When we receive a gateway timeout or not found status from their API we'll temporarily set your vacuum to unavailable, this will be resolved on the first successful API call afterwards.

We did this because otherwise the Homey app and your Neato might seem unresponsive, without the user knowing why.

**Comment by mickem** [comment]
Hmm... not sure this is a great solution.
Was this changed recently by the way?
Before the vacuum was working fine with my schedule but since the last update it has frequently been "not vacuuming" as it is unavailable when I schedule it to vacuum.

Since I installed a version which silently ignored the errors it started working again?

**Comment by MatthewWaanders** [comment]
To paint a clear picture:

We haven't changed our error handling and neither have Neato changed their API. 
The errors you're seeing now were already there, previously however the errors weren't reflected in the user interface.

As such, the behaviour of the app hasn't changed, when the Neato API isn't responding your robot will not respond to your Homey. The only thing that has changed is that we're now explicitly telling you it won't work.

I agree it isn't a perfect solution,  but this isn't a perfect scenario. In the perfect world everything would work as expected 100% of the time and we wouldn't have to set your device to unavailable when it doesn't.

**Comment by mickem** [comment]
Then I guess it is just that neato are responding with errors more frequently then before (the 404 response seem to be a bug with the API anyways)...
Well, guess there is not much to do about that...

Thanks for the clarification...
